
---
title: "Larval Krill Chamber Exposure Pilot Project CTD Data 2021 (import only)"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Larval Krill Chamber Exposure Pilot Project CTD Data 2021


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```



# Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(stringr)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
library(arsenal)
library(compareDF)
library(todor)
library(data.table)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
library(gdata)
library(rsq)
library(doBy)
library(lme4)
library(lmerTest)
#Rnotebooks 
library(gridExtra)
library(kableExtra)
library(todor)
#metadata
library(metacsv)

```




# 2.) Dataframe 
```{r}

#*********************************
## 2.) Creating the initial Dataframe
#*********************************

## 2.0 Reading in one file at a time
# looking to extract part of the character string from the file name
# something like:
# (substring(split(variables('Filename'),'_')

# Troubleshooting relative datapaths
setwd("/Users/katherinerovinski/Documents/GitHub/Krill-pilot-2021/raw_data/CTDcastData/2021.06.23")
getwd()
CTDfilesCast1 <- read_csv(here::here("raw_data", "CC1827005_20210623_070521.csv"))
CTDfilesCast1 <- read_csv(here::here("CTDcastData/2021.06.23", "CC1827005_20210623_070521.csv"))

CTDfilesCast2 <- read_csv(here::here("raw_data", "CC1827005_20210623_070614.csv"))


## 2.1 Create a list of files 
# All files to be joined have ext. "csv" can use that pattern to join 

setwd("/Users/katherinerovinski/Documents/GitHub/Krill-pilot-2021/raw_data/CTDcastData/2021.06.23")
getwd()
CTDfiles <- list.files(pattern = ".csv")
print(CTDfiles)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

setwd("/Users/katherinerovinski/Documents/GitHub/Krill-pilot-2021/raw_data/CTDcastData/2021.06.23")
temp <- lapply(CTDfiles, fread, sep= ",")
print(temp)
CTD_data_0623 <- rbindlist(temp)
print(CTD_data_0623)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# # Split dates using " _ "
# split_dates <- str_split(date_ranges, pattern = fixed(" _ "))
# # Split subsitutions and character string
# str_sub() and str_c()





write.csv(CTD_data_0623, file = "CTD_data_0623.csv", row.names = FALSE)

#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

```












```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT


